{
    'name': "Library Management",
    'summary': "Library Management",
    'description': "",
    'author': "Me",
    'website': "",
    'category': "Uncategorized",
    'version': '1.0',
    'depends': ['base','portal','web','product','website_sale','stock','website'],
    'assets': {
        'web.assets_frontend': [
            'web.core',
            'library_management_rushvi/static/src/js/main.js',
        ],
    },
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/borrow_request_sequence.xml',
        'report/borrow_history_report.xml',
        'report/borrow_request_report.xml',
        'wizard/borrow_status_canceled_views.xml',
        'wizard/reporting_books_history_views.xml',
        'views/library_books_views.xml',
        'views/library_students_views.xml',
        'views/library_librarians_views.xml',
        'views/library_borrow_requests_views.xml',
        'views/library_borrow_request_lines_views.xml',
        'views/product_template_inherit.xml',
        'views/res_config_settings_views.xml',
        'views/books_website_page.xml',
        'views/my_portal_page.xml',
        'views/students_website_page.xml',
        'views/librarian_website_page.xml',
        'views/website_menu_items.xml',
        'views/website_new.xml',
        'views/shop_template_new_filter.xml',
    ],
    'demo': [
        'demo/books_demo.xml',
        'demo/students_demo.xml',
        'demo/librarian_demo.xml',
        'demo/borrow_records_demo.xml',
        'demo/borrow_record_lines_demo.xml',
    ],
    'installable': True,
    'application': True,
    'license':'LGPL-3',
}