{
    'name': 'Library Management',
    'version': '1.0',
    'category': 'Uncategorized',
    'summary': 'Library Management Module',
    'description': "This is Library Management created by Tanisha",
    'website': 'https://www.librarymanagement.com',
    'depends': ['base','contacts','website','web'],
    'data': [
        'security/library_security.xml',
        'security/ir.model.access.csv',
        'data/borrow_request_seq.xml',
        'wizard/request_cancel_wizard_views.xml',
        'wizard/book_history_wizard_views.xml',
        'report/borrow_request_report.xml',
        'report/borrow_history_report.xml',
        'views/book_views.xml',
        'views/student_views.xml',
        'views/librarian_views.xml',
        'views/borrow_request_views.xml',
        'views/borrow_request_lines_views.xml',
        'views/fine_res_config_setting_views.xml',
        'views/website_page_views.xml',
        'views/book_website_views.xml',
        'views/my_account_borrow_request.xml',
        'views/reporting_submenu_website.xml',
        # 'views/custom_header_footer_website.xml',
        'views/library_website.xml',
    ],
    'demo': [
        'demo/book_demo_data.xml',
        'demo/student_demo_data.xml',
        'demo/borrow_records_demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'author': 'Tanisha',
    'license': 'LGPL-3',
}
