{
    'name': 'Hospital Management',
    'version': '1.0',
    'category': 'uncategorized',
    'summary': 'Summary of Hospital Management',
    'description': "This Hospital Management Module created by Tanisha",
    'website': 'https://www.hospitalmanagement.com',
    'depends': ['base','contacts'],
    'data': [
        'security/hospital_security.xml',
        'security/ir.model.access.csv',
        'demo/patient_demo_data.xml',
        'demo/department_demo_data.xml',
        'demo/hospital_demo_data.xml',
        'demo/appointment_demo_data.xml',
        'demo/doctor_demo_data.xml',
        'demo/hospital_demo_user.xml',
        'data/patient_seq.xml',
        'data/doctor_seq.xml',
        'wizard/create_department_wizard_views.xml',
        'wizard/create_appointment_wizard_views.xml',
        'views/hospital_base_views.xml',
        'views/hospital_views.xml',
        'views/department_views.xml',
        'views/inherit_patient_views.xml',
        'views/inherit_doctor_views.xml',
        'views/appointment_views.xml',
    ],
    'application': True,
    'installable': True,
    'author': 'Tanisha',
    'license': 'LGPL-3',
}
