{
    'name': "Car Rental Management",
    'summary': "Car Rental Management Rushvi",
    'description': "",
    'author': "Me",
    'website': "",
    'category': "Uncategorized",
    'version': '1.0',
    'depends': ['base','web','mail','website','portal','sale','point_of_sale'],
    'demo':[
        'demo/cars_category.xml',
        ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'demo/cars_category.xml',
        'data/vehicle_sequence.xml',
        'data/driver_sequence.xml',
        'data/car_rental_sequence.xml',
        'views/views_cars.xml',
        'views/views_drivers.xml',
        'views/views_car_booking.xml',
        'views/views_maintenance.xml',
        'views/customer_portal.xml',
        'views/car_rental_request_form.xml',
        'report/car_booking_report.xml',
    ],
    'installable': True,
    'application': True,
    'license':'LGPL-3',
}