{
    'name': "Car Rental Management",
    'summary': "Car Rental Management Rushvi",
    'description': "",
    'author': "Me",
    'website': "",
    'category': "Uncategorized",
    'version': '1.0',
    'depends': ['base', 'web', 'mail', 'website', 'portal', 'sale', 'point_of_sale','pos_restaurant'],
    'demo': [
        'demo/cars_category.xml',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'demo/cars_category.xml',
        'data/vehicle_sequence.xml',
        'data/driver_sequence.xml',
        'data/car_rental_sequence.xml',
        'views/views_cars.xml',
        'views/views_drivers.xml',
        'views/views_car_booking.xml',
        'views/views_maintenance.xml',
        'views/customer_portal.xml',
        'views/car_rental_request_form.xml',
        'report/car_booking_report.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'car_rental_management_rushvi/static/src/app/components/navbar/navbar.js',
            'car_rental_management_rushvi/static/src/app/components/navbar/navbar.xml',
            'car_rental_management_rushvi/static/src/app/components/popups/hide_details_button.js',
            'car_rental_management_rushvi/static/src/app/components/popups/hide_details_button.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
