{
    'name': "Hospital Management",
    'summary': "Hospital Management Rushvi",
    'description': "",
    'author': "Rushvi Doshi",
    'website': "",
    'category': "Uncategorized",
    'version': '1.0',
    'depends': ['base',],
    'demo':[
        'demo/hospital_demo.xml',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'demo/department_demo.xml',
        'demo/doctor_demo.xml',
        'demo/hospital_demo.xml',
        'demo/appointment_demo.xml',
        'data/doctor_sequence_data.xml',
        'data/patient_sequence_data.xml',
        'wizard/create_appointment_wizard.xml',
        'wizard/create_department_wizard.xml',
        'views/hospitals_views.xml',
        'views/patients_views.xml',
        'views/doctors_views.xml',
        'views/appointments_views.xml',
        'views/departments_views.xml',
        'report/patient_report.xml',
    ],
    'installable': True,
    'application': True,
    'license':'LGPL-3',
}