{
    'name': 'School Management',
    'version': '1.3',
    'category': 'Uncategorized',
    'summary': 'This is summary',
    'description': "This is school management system",
    'depends': ['base','mail','sale_management','contacts'],
    'website': 'https://www.school.gov.in',
    'data': [
        'security/ir.model.access.csv',
        'views/base_views.xml',
        'views/student_views.xml',
        'views/teacher_views.xml',
        'views/class_views.xml',
        'views/subject_views.xml',
        'views/school_views.xml',
        'views/admission_views.xml',
        'views/sale_order_inherit_views.xml',
        'views/res_partner_inherit_views.xml',
    ],
    'application': True,
    'installable': True,
    'author':'School',
    'license': 'LGPL-3',
}
