{
    'name': 'Project Management',
    'version': '1.0',
    'category': 'Uncategorized',
    'summary': 'Project Management',
    'description': "",
    'author': 'ME',
    'website': '',
    'depends': ['base','sale',],
    'demo': [
        # 'demo/stage_demo.xml',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'data/mail_server.xml',
        'demo/stage_demo.xml',
        'views/project_project_view.xml',
        'views/project_task_view.xml',
        'views/project_stage_view.xml',
        'views/project_timesheet_view.xml',
        'views/project_per_hour_rate_view.xml',
        'views/res_config_settings_views.xml',
        'views/schedule_action.xml',
        'report/project_bills.xml',
        # 'report/project_data_bill.xml',
        'wizard/bill_wizard_view.xml',
    ],
    'installable': True,
    'license':'LGPL-3',
    'application': True,
}